Blog app, create data model
firstpj/blog-app pull request #1
Opened 2023-11-03 01:18 UTC by firstpj

In this task, I accomplished the following steps:

1. Developed a new Rails application and assigned it a meaningful name, "blog-app."
2. Initialized the project using Git version control.
3. Ensured that the project included a Postgres database setup after creating the Rails application.
4. Constructed the project schema using the following methods:
   a. Created and executed necessary migration files.
   b. Ensured that table and column names align with the Entity-Relationship Diagram (ERD) provided. Note that the "photo" column in the "users" table should be a hyperlink to an image.
   c. Included foreign keys in the schema. Specifically, in the "posts" table, the column serving as the foreign key linking to the "users" table was named "author_id."
   d. Established corresponding indexes for all columns functioning as foreign keys.
5. Utilized the "sneak peek" section as a reference for any queries related to table or column names or data relationships.

2023-11-03 01:59 UTC, roshan-bajgain approved these changes

2023-11-03 02:09 UTC, roshan-bajgain reviewed
Hi @firstpj, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the linter is not checked. Please make sure to run the linter and submit the project again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-03 02:35 UTC, roshan-bajgain commented
Hello @firstpj, Please follow the step from here https://github.com/microverseinc/linters-config/tree/master/ror

2023-11-03 07:28 UTC, topeogunleye commented
Hi @firstpj, Can you please try closing your pull request, then re-opening it to trigger the linters.

2023-11-03 07:57 UTC, topeogunleye commented on .github/workflows/linters.yml
> +on: pull
on: push

2023-11-03 09:42 UTC, topeogunleye commented
Hi @firstpj, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

2023-11-03 13:28 UTC, joel-kalema reviewed
Hi @firstpj 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 

![pirates-of-the-caribbean-johnny-depp](https://user-images.githubusercontent.com/57408419/242635897-074a8afb-6646-4281-8ff9-8390f857a9c5.gif)


- [ ] You have submitted a project that has linters that do not pass, make sure you solve them and then ask again for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-04 10:18 UTC, KayLemba requested changes
Hi @firstpj    👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
- No linter errors. ✔️
- Git flow is followed. ✔️
- migrations correctly set up

Required Changes ♻️
Check the comments under the review in the inline comments.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-04 10:18 UTC, KayLemba commented on config/environments/production.rb
>  Rails.application.configure do
While you did a good job working on the project there is an important aspect you missed out in your database yml file. You are using the wrong database adapter please take a look at the screenshot below:
![Screenshot 2023-11-04 at 12 11 10 PM](https://github.com/firstpj/blog-app/assets/79506105/f56c3c56-dd5b-4186-aff8-e69dc398a4b8)

you used sqlite3 as your adapter the correct adapter to use is this:
default: &default
adapter: postgresql
encoding: unicode

...

2023-11-04 11:22 UTC, AbayomiOlaoye approved these changes
## STATUS: APPROVED :green_circle:  

Hi @firstpj  :wave: :wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Cleanly written code :white_check_mark: 
- PostgreSQL adapter was used ✅ 
- Nicely implemented models ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-04 12:34 UTC, merged